title: Neurodesk
logo: /assets/img/logo.png
description: A flexible, scalable, and easy to use data analysis environment for reproducible neuroimaging
show_downloads: true
theme: jekyll-theme-minimal
